### PR TITLE
Update Dockerfile to the latest Ruby version

### PR DESCRIPTION
**Pull request by parndt**
# Type of PR (feature, enhancement, bug fix, etc.)

Enhancement

## Description

I noticed while investigating #9 that the Ruby version is hardcoded.

In lieu of fixing that just yet I thought I could at least bring it up to date.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] Actions are passing

### CODE REVIEW

**Comment by parndt** [comment]
@searls oh dear - the project tries to bundle but there is no Gemfile, and it tries to run `bin/rspec` but that file doesn't exist.

Would you like me to set those things up?

**Comment by searls** [comment]
Full disclosure: I've never actually used this action but I very much want to, and I fully believe it needs work to be useful. 

If you'd be willing to help out in pushing it forward I would really appreciate. Since I know and trust you (as co-maintainer of the Emoruby programming language), feel free to do whatever has to be done

**Comment by parndt** [comment]
> (as co-maintainer of the Emoruby programming language)

✨ 💖 ✅ 

sounds good, I'll investigate..

**Comment by searls** [comment]
Obviated by #15

**Pull request closed without merging**
